### ISSUE TITLE
Bis zur Abgabe

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Client#79]
Dominik
- [x] #66 (implemented not merged) (Montag, 01.06)
- [x] #29 (Mittwoch, 03.06)
- [x] #77 (gefixed von Marco, PR offen) (Mittwoch, 03.06)
- [x] #33 (Basic implementierung von Marco auf featureGameOver) (Freitag 05.06)
- [x] #72 (Montag 08.06)

Marco 
- [x] #61 
- [x] #73 
- [x] #78 
- [x] #74 
- [x] #69 
- [x] #76 
- [x] #86 
- [x] Enter Stakes for roulette
- [x] Display if prev. op. was successful
